name: Build and Publish Electron App
on:
  push:
    branches: [ main ]
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.16.0'
    
    - name: Install Dependencies
      run: npm install

    - name: Build Electron App
      run: npm run make

    - name: Publish
      run: npm run publish

    - name: LS folder
      run: ls -l ./out
      continue-on-error: true

    - name: Set token as env
      run: export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: out/*/*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: "v1.0.0"
        draft: false
